ALTER TABLE users
DROP COLUMN IF EXISTS email,
DROP COLUMN IF EXISTS name;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS user_name VARCHAR(255) UNIQUE;


ALTER TABLE xrp_accounts
DROP COLUMN IF EXISTS balance;
